# Tehran Project — Numerical Screening

NumPy is used to create a numerical screening layer for urban indicators before spatial analysis, modeling, and site-selection decisions.

In [2]:
import numpy as np

In [3]:
district_id = np.array([
    1, 2, 3, 4, 5,
    6, 7, 8, 9, 10
])

distance_to_metro = np.array([
    250, 420, 580, 900, 1100,
    760, 340, 1250, 650, 480
])

green_coverage = np.array([
    18, 12, 9, 6, 5,
    11, 15, 4, 8, 13
])

pm25 = np.array([
    32, 38, 42, 51, 55,
    44, 35, 58, 47, 39
])

## Urban Indicator Profile

Basic descriptive statistics are calculated to establish the numerical range and central tendency of selected urban indicators.

In [4]:
print("Metro Distance")
print("Mean:", distance_to_metro.mean())
print("Median:", np.median(distance_to_metro))
print("Min:", distance_to_metro.min())
print("Max:", distance_to_metro.max())

print("\nGreen Coverage")
print("Mean:", green_coverage.mean())
print("Median:", np.median(green_coverage))

print("\nPM2.5")
print("Mean:", pm25.mean())
print("Median:", np.median(pm25))

Metro Distance
Mean: 673.0
Median: 615.0
Min: 250
Max: 1250

Green Coverage
Mean: 10.1
Median: 10.0

PM2.5
Mean: 44.1
Median: 43.0


## Accessibility Screening

A threshold-based mask is used to flag observations that may require further accessibility analysis.

In [5]:
poor_metro_access = distance_to_metro > 800

poor_metro_access

array([False, False, False,  True,  True, False, False,  True, False,
       False])

In [6]:
district_id[poor_metro_access]

array([4, 5, 8])

In [7]:
distance_to_metro[poor_metro_access]

array([ 900, 1100, 1250])

In [8]:
poor_access_share = poor_metro_access.mean() * 100

print(
    "Poor-access observations:",
    poor_metro_access.sum()
)

print(
    "Share:",
    round(poor_access_share, 1),
    "%"
)

Poor-access observations: 3
Share: 30.0 %


## Multi-Indicator Screening

Multiple urban indicators are combined to identify observations where accessibility, environmental quality, and green coverage may simultaneously require further investigation.

In [9]:
poor_access = distance_to_metro > 800
low_green = green_coverage < 10
high_pollution = pm25 > 45

In [10]:
combined_mask = (
    poor_access
    & low_green
    & high_pollution
)

In [11]:
district_id[combined_mask]

array([4, 5, 8])

In [12]:
print(
    "District:",
    district_id[combined_mask]
)

print(
    "Metro Distance:",
    distance_to_metro[combined_mask]
)

print(
    "Green Coverage:",
    green_coverage[combined_mask]
)

print(
    "PM2.5:",
    pm25[combined_mask]
)

District: [4 5 8]
Metro Distance: [ 900 1100 1250]
Green Coverage: [6 5 4]
PM2.5: [51 55 58]


## Screening Flag

A reusable analytical flag is created for observations that satisfy the current screening conditions.

In [13]:
screening_flag = np.where(
    combined_mask,
    "Review",
    "Normal"
)

screening_flag

array(['Normal', 'Normal', 'Normal', 'Review', 'Review', 'Normal',
       'Normal', 'Review', 'Normal', 'Normal'], dtype='<U6')

In [14]:
for district, flag in zip(
    district_id,
    screening_flag
):
    print(district, flag)

1 Normal
2 Normal
3 Normal
4 Review
5 Review
6 Normal
7 Normal
8 Review
9 Normal
10 Normal


## Distribution-Based Screening

Percentiles provide data-driven thresholds for identifying observations located in the extreme parts of an urban indicator distribution.

In [15]:
metro_p75 = np.percentile(
    distance_to_metro,
    75
)

metro_p75

np.float64(865.0)

In [16]:
farther_observations = (
    distance_to_metro >= metro_p75
)

district_id[farther_observations]

array([4, 5, 8])

## Tehran Project — Session 10 Outcome

NumPy was used to profile urban indicators, create threshold- and percentile-based masks, and combine multiple conditions into a reproducible urban screening layer.

These results are exploratory and do not represent final site-selection decisions.